#build
FROM node:22-alpine
ARG BUILD_CONTEXT

WORKDIR /base
COPY package.json yarn.lock .yarnrc.yml tsconfig.json ./
COPY .yarn ./.yarn
COPY ./packages ./packages
COPY ./$BUILD_CONTEXT/ ./$BUILD_CONTEXT/
COPY ./backend/ecosystem.config.cjs ./backend/ecosystem.config.cjs
RUN yarn set version berry

WORKDIR /base/$BUILD_CONTEXT
RUN yarn install --network-timeout 1000000
RUN yarn build
RUN npm install -g pm2
CMD ["pm2-runtime", "start", "ecosystem.config.cjs"]