config:
  gcp:project: lang-learning-prod
  gcp:region: us-central1
  lang-learning:appPath: app
  lang-learning:concurrency: '50'
  lang-learning:containerPort: '8080'
  lang-learning:cpu: '4'
  lang-learning:memory: 4Gi
